### ISSUE TITLE
In what order do the modes switch?

### ISSUE THREAD

**Issue by Seairth** [NorviewFIRSTRobotics/Robot2016#11]
When a match starts, do they start in the Disabled mode?  Or does it always progress:

Start->Auto -> Teleop -> Disabled

(in this case Start is just the initial condition while it waits for the first "Auto" message from the control station.)

Also, I vaguely recall that the robot could be set to disabled at any time.  So I assume these are also possible transitions:

Start -> Auto -> Disabled
Start -> Disabled

If that's the case, then I think that autonomousInit() can simply be:

`setActivity(getDefaultActivity)`

Leave teleopInit() empty.  We'll just let the autonomy code implicitly switch to ManualDrive when it calls getDefaultActivity().  That way, as I mentioned in the other thread, autonomy can finish whatever its current activity is.

In disabledInit(), it can just be:

`currentActivity.Cancel()`

This will both stop whatever the current activity is and set the current activity to Idle (assuming that Cancel() calls `robot.setActivity(robot.getDefaultActivity())`).

**Comment by primetoxinz** [comment]
there is definitely a Start condition, where all possibilities are false, when the Robot is initialized.
It then simple goes through each possibility every "tick" to see what the drivestation is set to, there doesn't seem to be an order programmatically. but we do know how the competition will be, there should never be a way to go from teleop to autonomous in the actual competition
