### ISSUE TITLE
Issues getting Ultrasonic pairing functioning

### ISSUE THREAD

**Issue by primetoxinz** [NorviewFIRSTRobotics/Robot2016#13]
When setting up the ultrasonics, having the "automatic mode" set to false would stop the echo signal from sending anything. I will be debugging this more tomorrow in my free block, but I am very confused by it

**Comment by Seairth** [comment]
If I am recalling correctly, you are creating two Ultrasonic objects.  If you enable automatic mode, then the objects each take turns pinging.  If you have automatic mode off, then you need to initiate the ping yourself.  Unfortunately, I don't remember how to do it manually.  Was it enough to simply get the distance?
