### ISSUE TITLE
Find a better way to handle states

### ISSUE THREAD

**Issue by primetoxinz** [NorviewFIRSTRobotics/Robot2016#6]
I'm not happy with the way I have done it and frankly have no idea how to do it correctly.

**Comment by Seairth** [comment]
That's fine.  States are hard to get right, particularly when we don't have a well-defined state diagram to work from.  We'll come back to this.  But first, I want to tackle some of the higher-level concepts (in a separate thread).

**Comment by primetoxinz** [comment]
Supposed this is fixed for the moment
